version: "3.7"
services:
  service:
    build: .
    image: kotlin-vertx-example/rest-service
    depends_on:
      - database
      - cache
      - sqs
    ports:
      - "8080:8080"
  database:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "./dockercompose/mongo/:/data/db"
    ports:
      - "27017:27017"
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
  sqs:
    image: s12v/elasticmq:latest
    volumes:
      - "./dockercompose/elasticmq/:/etc/elasticmq/"
    ports:
      - "9324:9324"
